---
- hosts: 'test_server'
  become: yes
  vars:
    - script: "./nmapVulners.sh"
    - stylesheet: "./nmap-bootstrap.xsl"
    - target: ./targets.txt
    - cadence: "25 14 * * *"
    - recipients: "la.ambojia@gmail.com"
    - sender: "kartero@mailer.alipyo.com"
    - installpath: "/usr/local/bin/nmap-vulners/"
    - vulnerspath: "/usr/share/nmap/scripts/vulners.nse"
  tasks:
  - name: Install Package Dependencies
    apt:
      pkg:
       - nmap
       - xsltproc
      state: latest
      update_cache: yes
  - name: Download Vulners Script
    get_url:
      url: "https://raw.githubusercontent.com/vulnersCom/nmap-vulners/master/vulners.nse"
      dest: "{{vulnerspath}}"
  - name: Update Nmap Script DB
    shell: |
      nmap --script-updatedb
  - name: Create Script Install directory
    file:
      path: "{{ installpath }}"
      state: directory
  - name: Copy Targets to Install directory
    copy:
      src: "{{ target }}"
      dest: "{{ installpath }}"
      owner: root
      group: root
      mode: 0400
    register: _target
  - name: Copy Stylesheet to Install directory
    copy:
      src: "{{ stylesheet }}"
      dest: "{{ installpath }}"
      owner: root
      group: root
      mode: 0400
    register: _stylesheet
  - name: Copy Script to Install directory
    copy:
      src: "{{ script }}"
      dest: "{{ installpath }}"
      owner: root
      group: root
      mode: u+rwx,g-wx,o-rwx
    register: _script
  - name: Install Script
    shell: |
      bash {{ _script.dest }} -i {{ _target.dest }} -v {{ vulnerspath }} -s {{ _stylesheet.dest }} -r {{ recipients }} -f {{ sender }} -I "{{ cadence }}"