- name: 'Check mandatory variables are defined'
  assert:
    that:
      - recipients is defined
      - cadence is defined
      - installpath is defined
      - vulnerspath is defined
      - script is defined
      - stylesheet is defined
      - mincvss is defined

- name: Install Package Dependencies
  apt:
    pkg:
     - nmap
     - xsltproc
     - s-nail
     #- mailutils
    state: latest
    update_cache: yes

- name: Download Vulners Script
  get_url:
    url: "https://raw.githubusercontent.com/vulnersCom/nmap-vulners/master/vulners.nse"
    dest: "{{vulnerspath}}"

- name: Update Nmap Script DB
  shell: |
    nmap --script-updatedb

- name: Create Script Install directory
  file:
    path: "{{ installpath }}"
    state: directory

- name: Build Inventory
  template:
    src: targets.j2
    dest: "{{installpath}}"
    owner: root
    backup: yes
  register: _inventory
  when: target is undefined

- name: Copy Stylesheet to Install directory
  copy:
    src: "{{stylesheet}}"
    dest: "{{installpath}}"
    owner: root
    group: root
    mode: 0400
  register: _stylesheet

- name: Copy Script to Install directory
  copy:
    src: "{{ script }}"
    dest: "{{ installpath }}"
    owner: root
    group: root
    mode: u+rwx,g-wx,o-rwx
  register: _script

- name: Set Install String (Inventory)
  set_fact:
    install_string: bash {{ _script.dest }} -i {{ _inventory.dest }} -v {{ vulnerspath }} -m {{mincvss}} -s {{ _stylesheet.dest }} -r '{{ recipients }}' -f '{{ sender }}' -I '{{ cadence }}'
  when: target is undefined

- name: Set Install String (Solo)
  set_fact:
    install_string: bash {{ _script.dest }} -t {{ target }} -v {{ vulnerspath }} -m {{mincvss}} -s {{ _stylesheet.dest }} -r '{{ recipients }}' -f '{{ sender }}' -I '{{ cadence }}'
  when: target is defined

- name: Install Script
  shell: "{{install_string}}"
  register: result

- name: Show full result
  debug:
    var: result.stdout

